### ISSUE TITLE
Allow setting keys in outbox messages

### ISSUE THREAD

**Issue by mgibowski** [v0idpwn/kafkaesque#1]
## The problem

At the moment, published messages have always an empty key:
https://github.com/v0idpwn/kafkaesque/blob/2c43100ebd488c6a58f6a48113bf653a08a70c56/lib/kafkaesque/clients/brod_client.ex#L42

This prevents key-based retention via topic compaction:
https://developer.confluent.io/courses/architecture/compaction/#topic-compaction-key-based-retention

## The solution

That would be a breaking change, but I think the `MyApp.Outbox.publish/2` function should accept three arguments and become:

`MyApp.Outbox.publish("topic", "key", %{hello: :kafka})`

Similarly, the `Kafkaesque.publish/4` function would become `Kafkaesque.publish/5` and accept `key` argument just before the `payload`.

And the structure of `Kafkaesque.Message` schema would be extended with the `key` field.

---

@v0idpwn  What do you think?

**Comment by v0idpwn** [comment]
Hi, @mgibowski. I agree we should support `key`, I'm not 100% sure we should make it required, though, as its very common to use empty keys in Kafka.

`:brod` has the following interface:
- [produce_sync(Pid, Value)](https://hexdocs.pm/brod/brod.html#produce_sync/2)
- [produce_sync(Pid, Key, Value)](https://hexdocs.pm/brod/brod.html#produce_sync/3)

Perhaps we could follow along and have `publish(topic, key, payload)` and `publish(topic, payload)`? (i.e.: this would be `publish(topic, key \\ "", payload)`

**Comment by mgibowski** [comment]
> Perhaps we could follow along and have publish(topic, key, payload) and publish(topic, payload)? (i.e.: this would be publish(topic, key \\ "", payload)

Yes, that makes sense!

**Comment by v0idpwn** [comment]
I started #2 adding this feature. It will be a breaking change, but I'll try to make it smooth.
Do you intend to use Kafkaesque in production? I can try to cut 1.0 for that :)

**Comment by mgibowski** [comment]
> I started https://github.com/v0idpwn/kafkaesque/pull/2 adding this feature. It will be a breaking change, but I'll try to make it smooth.

So far looks great!

> Do you intend to use Kafkaesque in production? I can try to cut 1.0 for that :)

Yes, we plan to release code that uses Kafkaesque to production in middle November. 1.0 by that time would be awesome :)
